services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:develop
    container_name: sonarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "${SONARR_PORT:-8989}:8989"
    volumes:
      - sonarr-config:/config
      - ${MEDIA_DIR:-/data/media}:/data/media
      - ${DOWNLOADS_DIR:-/data/downloads}:/data/downloads
    environment:
      TZ: ${TZ:-Etc/UTC}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}

volumes:
  sonarr-config:
