services:
  opint:
    image: opint:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: opint
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      OPENAI_API_BASE: ${OPENAI_API_BASE:-}
    volumes:
      - opint-config:/root/.config/open-interpreter

volumes:
  opint-config:
