services:
  optillm:
    image: optillm:latest
    build:
      context: https://github.com/codelion/optillm.git#main
      dockerfile: Dockerfile
    container_name: optillm
    ports:
      - "${OPTILLM_PORT:-8000}:8000"
    volumes:
      - optillm-config:/root/.config/optillm

volumes:
  optillm-config:
