services:
  wud:
    image: fmartinou/whats-up-docker:latest
    container_name: wud
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "${WUD_HOST_PORT:-3000}:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      WUD_WATCHER_LOCAL_CRON: "0 1 * * *"
      WUD_WATCHER_LOCAL_WATCHALL: "true"
