services:
  flowise:
    image: flowiseai/flowise:latest
    container_name: flowise
    ports:
      - ${FLOWISE_HOST_PORT:-3000}:3000
    volumes:
      - flowise_data:/root/.flowise

volumes:
  flowise_data:
