services:
  stt:
    image: fedirz/faster-whisper-server:latest-cpu
    container_name: stt
    ports:
      - "${STT_HOST_PORT:-8000}:8000"
    volumes:
      - stt-hf-cache:/root/.cache/huggingface

volumes:
  stt-hf-cache:
