services:
  aichat:
    image: sigoden/aichat:latest
    container_name: aichat
    ports:
      - ${AICHAT_PORT:-8080}:8080
    volumes:
      - aichat_config:/root/.config/aichat

volumes:
  aichat_config:
