services:
  tabbyapi:
    image: nschle/tabbyapi:latest
    container_name: tabbyapi
    ports:
      - "${TABBYAPI_HOST_PORT:-5000}:5000"
    environment:
      NAME: TabbyAPI
    volumes:
      - tabbyapi-hf-models:/models/hf
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  tabbyapi-hf-models:
