services:
  notifiarr:
    image: golift/notifiarr:latest
    container_name: notifiarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "${NOTIFIARR_HOST_PORT:-5454}:5454"
    volumes:
      - notifiarr-config:/config
      - /var/run/utmp:/var/run/utmp:ro
      - /etc/machine-id:/etc/machine-id:ro
    environment:
      DN_API_KEY: ${NOTIFIARR_API_KEY}
      TZ: ${TZ:-Etc/UTC}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}

volumes:
  notifiarr-config:
