services:
  maintainerr:
    image: ghcr.io/jorenn92/maintainerr:latest
    container_name: maintainerr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "${MAINTAINERR_PORT:-6246}:6246"
    user: "${PUID:-1000}:${PGID:-1000}"
    volumes:
      - maintainerr-data:/opt/data
    environment:
      TZ: ${TZ:-Etc/UTC}

volumes:
  maintainerr-data:
